api_version = "2024-07"

[[extensions]]
name = "Custom Fields"
handle = "custom-fields-extension"
type = "ui_extension"


[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"


[extensions.capabilities]
api_access = true

network_access = true


[extensions.settings]
 [[extensions.settings.fields]]
  key = "form_name"
  type = "single_line_text_field"
  name = "Form Name"
  description = "Enter FORM NAME that you created on app"
