# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8bfa5c9a03d85943ff39537757b47a7c"
name = "checkout-app-test"
handle = "checkout-app-test-30"
application_url = "https://3a2d-39-58-102-216.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-maryam97.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_payment_customizations,write_products,write_validations"

[auth]
redirect_urls = [
  "https://3a2d-39-58-102-216.ngrok-free.app/auth/callback",
  "https://3a2d-39-58-102-216.ngrok-free.app/auth/shopify/callback",
  "https://3a2d-39-58-102-216.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://3a2d-39-58-102-216.ngrok-free.app"
subpath = "api"
prefix = "apps"

[pos]
embedded = false
