# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e64cc53951817f4a5a3045a61055ef35"
name = "checkout-app-main"
handle = "checkout-app-main"
application_url = "https://thrown-cole-announces-arbitration.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-ui-testing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://thrown-cole-announces-arbitration.trycloudflare.com/auth/callback",
  "https://thrown-cole-announces-arbitration.trycloudflare.com/auth/shopify/callback",
  "https://thrown-cole-announces-arbitration.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
