# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "48d53a05f9186135d3b5184776cfbd4f"
name = "remix-checkout-app"
handle = "remix-checkout-app"
application_url = "https://modification-taxation-intake-extends.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-ui-testing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_customizations,write_products,write_validations"

[auth]
redirect_urls = [
  "https://modification-taxation-intake-extends.trycloudflare.com/auth/callback",
  "https://modification-taxation-intake-extends.trycloudflare.com/auth/shopify/callback",
  "https://modification-taxation-intake-extends.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
