# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8bfa5c9a03d85943ff39537757b47a7c"
name = "checkout-app-test"
handle = "checkout-app-test-30"
application_url = "https://supervision-barbara-guitar-workshop.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-maryam97.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_payment_customizations,write_products,write_validations"

[auth]
redirect_urls = [
  "https://supervision-barbara-guitar-workshop.trycloudflare.com/auth/callback",
  "https://supervision-barbara-guitar-workshop.trycloudflare.com/auth/shopify/callback",
  "https://supervision-barbara-guitar-workshop.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
